### ISSUE TITLE
App_Start folder not created when installing Ninject.Extensions.Wcf from NuGet

### ISSUE THREAD

**Issue by fieldb** [ninject/Ninject.Extensions.Wcf#33]
After creating a new Wcf Service Application using Visual Studio 2013 and installing Ninject.Extensions.Wcf using Nuget there is no App_Start folder created nor a NinjectWebCommon class. 

Also, after creating a new Web Site using the Wcf Service template and installing Ninject.Extensions.Wcf using Nuget there is still no App_Start folder created nor a NinjectWebCommon class. 

Finally, after creating a new Web Site using the Wcf Service template hosted in IIS and installing Ninject.Extensions.Wcf using Nuget there is still no App_Start folder created nor a NinjectWebCommon class.

**Comment by scott-xu** [comment]
Please use Ninject.Extensions.Wcf.WebHost

**Comment by fieldb** [comment]
Issue resolved. Thank you.
